# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/johng/repos/Rasteriser

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/johng/repos/Rasteriser

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/johng/repos/Rasteriser/CMakeFiles /Users/johng/repos/Rasteriser/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/johng/repos/Rasteriser/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Main

# Build rule for target.
Main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Main
.PHONY : Main

# fast build rule for target.
Main/fast:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/build
.PHONY : Main/fast

Source/Camera.o: Source/Camera.cpp.o

.PHONY : Source/Camera.o

# target to build an object file
Source/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Camera.cpp.o
.PHONY : Source/Camera.cpp.o

Source/Camera.i: Source/Camera.cpp.i

.PHONY : Source/Camera.i

# target to preprocess a source file
Source/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Camera.cpp.i
.PHONY : Source/Camera.cpp.i

Source/Camera.s: Source/Camera.cpp.s

.PHONY : Source/Camera.s

# target to generate assembly for a file
Source/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Camera.cpp.s
.PHONY : Source/Camera.cpp.s

Source/Lighting.o: Source/Lighting.cpp.o

.PHONY : Source/Lighting.o

# target to build an object file
Source/Lighting.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Lighting.cpp.o
.PHONY : Source/Lighting.cpp.o

Source/Lighting.i: Source/Lighting.cpp.i

.PHONY : Source/Lighting.i

# target to preprocess a source file
Source/Lighting.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Lighting.cpp.i
.PHONY : Source/Lighting.cpp.i

Source/Lighting.s: Source/Lighting.cpp.s

.PHONY : Source/Lighting.s

# target to generate assembly for a file
Source/Lighting.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Lighting.cpp.s
.PHONY : Source/Lighting.cpp.s

Source/Main.o: Source/Main.cpp.o

.PHONY : Source/Main.o

# target to build an object file
Source/Main.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Main.cpp.o
.PHONY : Source/Main.cpp.o

Source/Main.i: Source/Main.cpp.i

.PHONY : Source/Main.i

# target to preprocess a source file
Source/Main.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Main.cpp.i
.PHONY : Source/Main.cpp.i

Source/Main.s: Source/Main.cpp.s

.PHONY : Source/Main.s

# target to generate assembly for a file
Source/Main.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Main.cpp.s
.PHONY : Source/Main.cpp.s

Source/Model.o: Source/Model.cpp.o

.PHONY : Source/Model.o

# target to build an object file
Source/Model.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Model.cpp.o
.PHONY : Source/Model.cpp.o

Source/Model.i: Source/Model.cpp.i

.PHONY : Source/Model.i

# target to preprocess a source file
Source/Model.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Model.cpp.i
.PHONY : Source/Model.cpp.i

Source/Model.s: Source/Model.cpp.s

.PHONY : Source/Model.s

# target to generate assembly for a file
Source/Model.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Model.cpp.s
.PHONY : Source/Model.cpp.s

Source/Rasteriser.o: Source/Rasteriser.cpp.o

.PHONY : Source/Rasteriser.o

# target to build an object file
Source/Rasteriser.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Rasteriser.cpp.o
.PHONY : Source/Rasteriser.cpp.o

Source/Rasteriser.i: Source/Rasteriser.cpp.i

.PHONY : Source/Rasteriser.i

# target to preprocess a source file
Source/Rasteriser.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Rasteriser.cpp.i
.PHONY : Source/Rasteriser.cpp.i

Source/Rasteriser.s: Source/Rasteriser.cpp.s

.PHONY : Source/Rasteriser.s

# target to generate assembly for a file
Source/Rasteriser.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Rasteriser.cpp.s
.PHONY : Source/Rasteriser.cpp.s

Source/Renderer.o: Source/Renderer.cpp.o

.PHONY : Source/Renderer.o

# target to build an object file
Source/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Renderer.cpp.o
.PHONY : Source/Renderer.cpp.o

Source/Renderer.i: Source/Renderer.cpp.i

.PHONY : Source/Renderer.i

# target to preprocess a source file
Source/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Renderer.cpp.i
.PHONY : Source/Renderer.cpp.i

Source/Renderer.s: Source/Renderer.cpp.s

.PHONY : Source/Renderer.s

# target to generate assembly for a file
Source/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Renderer.cpp.s
.PHONY : Source/Renderer.cpp.s

Source/SDLauxiliary.o: Source/SDLauxiliary.cpp.o

.PHONY : Source/SDLauxiliary.o

# target to build an object file
Source/SDLauxiliary.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/SDLauxiliary.cpp.o
.PHONY : Source/SDLauxiliary.cpp.o

Source/SDLauxiliary.i: Source/SDLauxiliary.cpp.i

.PHONY : Source/SDLauxiliary.i

# target to preprocess a source file
Source/SDLauxiliary.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/SDLauxiliary.cpp.i
.PHONY : Source/SDLauxiliary.cpp.i

Source/SDLauxiliary.s: Source/SDLauxiliary.cpp.s

.PHONY : Source/SDLauxiliary.s

# target to generate assembly for a file
Source/SDLauxiliary.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/SDLauxiliary.cpp.s
.PHONY : Source/SDLauxiliary.cpp.s

Source/Texture.o: Source/Texture.cpp.o

.PHONY : Source/Texture.o

# target to build an object file
Source/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Texture.cpp.o
.PHONY : Source/Texture.cpp.o

Source/Texture.i: Source/Texture.cpp.i

.PHONY : Source/Texture.i

# target to preprocess a source file
Source/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Texture.cpp.i
.PHONY : Source/Texture.cpp.i

Source/Texture.s: Source/Texture.cpp.s

.PHONY : Source/Texture.s

# target to generate assembly for a file
Source/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Texture.cpp.s
.PHONY : Source/Texture.cpp.s

Source/Triangle.o: Source/Triangle.cpp.o

.PHONY : Source/Triangle.o

# target to build an object file
Source/Triangle.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Triangle.cpp.o
.PHONY : Source/Triangle.cpp.o

Source/Triangle.i: Source/Triangle.cpp.i

.PHONY : Source/Triangle.i

# target to preprocess a source file
Source/Triangle.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Triangle.cpp.i
.PHONY : Source/Triangle.cpp.i

Source/Triangle.s: Source/Triangle.cpp.s

.PHONY : Source/Triangle.s

# target to generate assembly for a file
Source/Triangle.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/Source/Triangle.cpp.s
.PHONY : Source/Triangle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Main"
	@echo "... Source/Camera.o"
	@echo "... Source/Camera.i"
	@echo "... Source/Camera.s"
	@echo "... Source/Lighting.o"
	@echo "... Source/Lighting.i"
	@echo "... Source/Lighting.s"
	@echo "... Source/Main.o"
	@echo "... Source/Main.i"
	@echo "... Source/Main.s"
	@echo "... Source/Model.o"
	@echo "... Source/Model.i"
	@echo "... Source/Model.s"
	@echo "... Source/Rasteriser.o"
	@echo "... Source/Rasteriser.i"
	@echo "... Source/Rasteriser.s"
	@echo "... Source/Renderer.o"
	@echo "... Source/Renderer.i"
	@echo "... Source/Renderer.s"
	@echo "... Source/SDLauxiliary.o"
	@echo "... Source/SDLauxiliary.i"
	@echo "... Source/SDLauxiliary.s"
	@echo "... Source/Texture.o"
	@echo "... Source/Texture.i"
	@echo "... Source/Texture.s"
	@echo "... Source/Triangle.o"
	@echo "... Source/Triangle.i"
	@echo "... Source/Triangle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

